server.port=443
server.ssl.enabled=true
server.ssl.key-store=/etc/letsencrypt/live/mockcote.site/keystore.p12
server.ssl.key-store-password=${KEYSTORE_PASSWORD}
server.ssl.key-store-type=PKCS12
spring.application.name=frontend


spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

api.gateway.url=https://scg.mockcote.site

spring.task.scheduling.pool.size=5
logging.level.org.springframework.scheduling=DEBUG
